name: "Release"

# on:
#   push:
#     branches:
#       - "master"
on:  
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  setup:
    name: Setup
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2  
      - name: Set up GitHub package registry auth token
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Lint
        run: yarn lint
      - name: Build
        run: tsc
      - name: Generate Documentation
        run: |
          node dist/generate-docs.js
          ls -la
      - name: Commit and push change
        run: |
          git commit -am "üìù Update documentation for packages"
          git push
        